### ISSUE TITLE
Keep All Versions Available, Not Just Latest

### ISSUE THREAD

**Issue by timreuscher** [leonghui/bitwarden-web-alpine#2]
Given this bug - https://github.com/VictorNine/bitwarden-go/issues/24, is there any chance to keep all versions available in the docker repository, not just the latest? I'd love to be able to go back to 1.22.

That said, I was able to use the official bitwarden/web 1.22 docker with the your current bitwarden-go docker. Is there any reason to use your bitwarden-web vs. the official?

**Comment by leonghui** [comment]
Hi there, sorry for the inconvenience.  VictorNine/bitwarden-go#24 has been fixed so could you retry with my latest image (now based on v.1.24.0)?

Well I have not tested the official image for my use case (running Bitwarden on Synology NAS) so I can't comment on that. A small rewrite of the docker file will be needed to use bitwarden-web releases instead of the latest commit so I'll try to get that done over the weekend.

**Comment by timreuscher** [comment]
No worries. I'm on Synology too, and if anything, I think the bigger issue is likely the bitwarden-go getting too out of sync with bitwarden's official dockers. This week wasn't too bad, but there were a couple days where it just didn't function with updated iOS apps. But since I'm not knowledgable enough in this stuff to contribute, please don't take it as a complaint. I appreciate the effort!
